### ISSUE TITLE
Provide possibility to get response as JSON, XML or a DOC file

### ISSUE THREAD

**Issue by yehorsyrin** [ilantos/Movies.RESTful_API#2]
Crete something like

/xml/movie/{id}
/json/movie/{id}
/doc/movie/{id}

**Comment by ilantos** [comment]
**Now API looks like:**

- (type)/movie/id/{id}
- (type)/movie/title/{title}
- (type)/movie/search/{title}

_Where (type) is: json, xml, doc._

---
**Examples:**
json/movie/id/tt0096895
doc/movie/search/Batman
